# 空间数据

在 R 环境中，一切都是对象，一切操作都是函数调用。以最常见的绘图函数 `plot()` 为例，它是一个泛型函数，遇到不同的数据对象调用不同的绘图方法，在空间数据可视化领域，R 包 **sp** 和 **raster** 都提供扩展 `plot()` 的方法。读者可在控制台运行命令 `methods(plot)` 查看当前命名空间加载的所有方法，其中星号 \* 标记的是 S3 方法， @tbl-plot-methods 列出了当前可用的方法。

```{r}
library(sp)
library(raster)
library(sf)
```
```{r}
#| label: tbl-plot-methods
#| tbl-cap: "plot 方法"
#| echo: false
knitr::kable(matrix(data = methods(plot), ncol = 2, byrow = T),
  col.names = c("第一列", "第二列")
)
```

@fig-unemp-maps 呈现 2009 年美国各个城镇的失业率分布。

```{r}
#| label: fig-unemp-maps
#| fig-cap: "2009 年美国各个城镇的失业率分布"
#| fig-width: 9
#| fig-height: 7
#| fig-align: "center"
#| fig-showtext: true
#| collapse: true

# 代码调整自帮助文档 ?map
library(maps)
library(mapproj)
# 失业率数据
data(unemp)
# 行政编码
data(county.fips)
# 准备调色板
colors <- viridisLite::plasma(9)
# 失业率划分区间
unemp$colorBuckets <- as.numeric(cut(
  unemp$unemp, c(seq(0, 10, by = 2), 15, 20, 25, 100)
))
# 准备图例文本
leg.txt <- c(
  "<2%", "2-4%", "4-6%", "6-8%", "8-10%",
  "10-15%", "15-20%", "20-25%", ">25%"
)
# 地图数据和 FIPS 数据
cnty.fips <- county.fips$fips[match(
  map("county", plot = FALSE)$names,
  county.fips$polyname
)]
# 匹配上的区域
colorsmatched <- unemp$colorBuckets[match(cnty.fips, unemp$fips)]
par(mar = c(1.5, 0, 2, 0))
# 绘制区县地图
map("county",
  col = colors[colorsmatched], fill = TRUE, resolution = 0,
  lty = 0, projection = "polyconic", mar = c(0.5, 0.5, 2, 0.5)
)
# 添加州边界线
map("state",
  col = "white", fill = FALSE, add = TRUE,
  lty = 1, lwd = 0.2, projection = "polyconic"
)
# 添加图标题
title("2009 年美国各个城镇的失业率")
mtext(text = "数据源：美国人口调查局", side = 1, adj = 0)
# 添加图例
legend("top", leg.txt, horiz = TRUE, fill = colors, cex = 0.85)
```

